### ISSUE TITLE
Hier moet je een prepared statement gebruiken

### ISSUE THREAD

**Issue by hiddebraun-ma** [Iqgor/F2M4BAP#1]
https://github.com/Iqgor/F2M4BAP/blob/1354c7730bc22912a4223d28f77ab4e370b345dd/details.php#L29-L30

Anders kan ik door de id in de URL te veranderen je hele database leeg maken of erger.
Omdat jij en Roan niet de PDO manier gebruiken maar de mysqli extentie snap ik dat je dat niet meteen hebt gedaan.

Hier staat hulp (zie link) Pas de code aan zodat de query veilig wordt uitgevoerd met een prepared statement:
https://www.w3schools.com/php/php_mysql_prepared_statements.asp

**Comment by Iqgor** [comment]
Ik heb dit gefixed door jou methode te gebruiken en mijn eigen code er omheen te gebruiken. Dit kan je zien in de nieuwe commit.
